application:
  name: dev环境 spring-boot-demo-properties
  version: dev环境 1.0-SNAPSHOT
developer:
  name: dev环境 xkcoding
  website: dev环境 http://xkcoding.com
  qq: dev环境 237497819
  phone-number: dev环境 17326075631