application:
  name: prod环境 spring-boot-demo-properties
  version: prod环境 1.0-SNAPSHOT
developer:
  name: prod环境 ycb
  website: prod环境 www.baidu.com
  qq: prod环境 155345634
  phone-number: prod环境 123456789