server:
  port: 8080
  servlet:
    context-path: /mybaitsPlus

#数据库信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot-demo?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: hsp

#mybatisPlus信息
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ycb.demo.bean